version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./client/
      dockerfile: ./Dockerfile
    #depends_on: 
    #  - server
    volumes: 
      - ./client/build:/var/www/html
      - ./client/nginx.conf:/etc/nginx/sites-available/default
    ports: 
      - 80:80

  #frontend:
  #  build:
  #    context: ./client/
  #    dockerfile: Dockerfile.test
  #  ports:
  #    - '80:80'
  #    - '443:443'
  #  volumes:
  #    - ./frontend/build:/var/www/html
  #    - ./client/default.conf:/etc/nginx/sites-available/default
  #    - ./letsencrypt:/etc/letsencrypt
  #  depends_on:
  #    - server
