version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./
      dockerfile: ./Dockerfile.nginx
    depends_on: 
      - server
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80

  server:
    image: server
    container_name: server
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports: 
      - 8000:8000 #my machine : container
    restart: on-failure
  
  react:
    image: react
    container_name: react
    build: 
      context: ./client
    ports:
      - 3000:3000
    restart: on-failure