version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    build: 
      context: ./client/
      dockerfile: ./Dockerfile

    volumes: 
      - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80

  