version: '3'

services:

  react:
    image: nginx
    container_name: react
    build: 
      context: ./front/client/
    depends_on: 
      - server
    volumes: 
      - ./front/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80

  server:
    image: server
    container_name: server
    build: 
      context: ./back
    ports: 
      - 8000:8000 #my machine : container
    restart: on-failure